title: ITMO Docs (multiple disciplines)
description: Конспекты, etc.
theme: null
remote_theme: pages-themes/minima@v0.2.1
markdown: kramdown
kramdown:
  math_engine: mathjax
plugins:
  - jekyll-feed

